# Generated by Django 3.0.8 on 2020-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short',
            field=models.CharField(max_length=16, verbose_name='Short url'),
        ),
    ]
