# Generated by Django 3.0.8 on 2020-07-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20200714_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='used_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
